### ISSUE TITLE
Python 3.7 support

### ISSUE THREAD

**Issue by jayvdb** [welbornprod/requirementz#1]
Just noting quite a few levels beneath this is a Python 3.7 bug
https://github.com/welbornprod/colr/issues/7

**Comment by cjwelborn** [comment]
I saw the issue in the colr repo. I'll take care of it.

**Comment by cjwelborn** [comment]
Colr should be Python3.7-compatible now, and all tests for this project are passing on my end. I'm gonna go ahead and close this. Thank you for taking the time to let me know.

**Comment by jayvdb** [comment]
Thank you.  Yes, my Requirementz builds also pass despite the problem with https://github.com/welbornprod/colr/issues/8
